clean:
	rm -rf **/*.o **/*~ core **/*.depend **/.*.cmd **/*.ko **/*.mod.c **/*.tmp_versions **/*.dwo **/*.mod **/*.order **/Module.symvers
	rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions *.dwo *.mod *.order Module.symvers